version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: widblogbackend
    container_name: widblogbackend-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - widblogbackend

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: widblogbackend-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wid_blog_backend
      MYSQL_ROOT_PASSWORD: alimalik
      MYSQL_PASSWORD: alimalik
      MYSQL_USER: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - widblogbackend

  nginx:
    image: nginx:alpine
    container_name: widblogbackend-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - widblogbackend

networks:
  widblogbackend:
    driver: bridge