version: '3'

networks:
  widblogbackend:

volumes:
  db-laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - widblogbackend

  mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - db-laravel:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wid_blog_backend
      MYSQL_USER: root
      MYSQL_PASSWORD: alimalik
      MYSQL_ROOT_PASSWORD: alimalik
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - widblogbackend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    restart: unless-stopped
    ports:
      - 8181:80
    networks:
      - widblogbackend
    depends_on:
      - mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - widblogbackend

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - widblogbackend

  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - widblogbackend